Henslowe/config/routes.rb
Henslowe::Application.routes.draw do
  root :to => 'theaters#index'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy"
  resources :authors

  resources :niches

  resources :theaters do |theater|
    resources :spaces
    resources :productions do
      member do
        get 'doubling'
        get 'bulk_scheduler'
      end
    end
    resources :users
    resources :jobs
  end

  resources :productions do
    resources :rehearsals
  end

  resources :plays do	
    resources :characters
    resources :acts do 
      resources :scenes do
        resources :french_scenes
      end
    end
  end

  resources :acts do 
    resources :scenes, :french_scenes
  end

  resources :scenes do 
    resources :french_scenes
  end

  resources :users do
    resources :productions
  end

end

Henslowe/app/models/theater.rb
class Theater < ActiveRecord::Base
  attr_accessible :mission_statement, :name, :state, :street_address, :city, :website, :zip, :phone_number, :productions_attributes, :calendar
  default_scope order(:name)
  has_many :productions, :dependent => :destroy
  has_many :plays, :through => :productions
  has_many :users, :through => :productions
  has_many :jobs
  has_many :users, :through => :jobs
  has_many :spaces, :dependent => :destroy

 def embed_calendar
    embed_code_start = "<iframe src=\"https://www.google.com/calendar/embed?showTitle=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src="
    embed_code_finish = "&amp;color=%23B1440E&amp;ctz=America%2FNew_York\" style=\" border-width:0 \" width=\"800\" height=\"600\" frameborder=\"0\" scrolling=\"no\"></iframe>"
    s = self.calendar
    embed = embed_code_start + s + embed_code_finish
  end
end

Henslowe/app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end
  
  def show
    @theater = Theater.find(params[:id])
  end
  
  def new
    @theater = Theater.new
  end
  
  def create
    @theater = Theater.new(params[:theater])
    if @theater.save
      flash[:notice] = "Successfully created theater."
      redirect_to @theater
    else
      render :action => 'new'
    end
  end
  
  def edit
    @theater = Theater.find(params[:id])
  end
  
  def update
    @theater = Theater.find(params[:id])
    if @theater.update_attributes(params[:theater])
      flash[:notice] = "Successfully updated theater."
      redirect_to @theater
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @theater = Theater.find(params[:id])
    @theater.destroy
    flash[:notice] = "Successfully destroyed theater."
    redirect_to theaters_url
  end
end

Henslowe/app/helpers/theaters_helper.rb
module TheatersHelper
end

Henslowe/app/views/theaters/_form.html.erb
<%= semantic_form_for @theater do |f| %>
  <%= f.inputs :name, :street_address, :city, :state, :zip, :phone_number, :website, :mission_statement, :calendar %>
  <%= f.actions %>
<% end %>

Henslowe/app/views/theaters/edit.html.erb
<% title "Edit Theater" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @theater %> |
  <%= link_to "View All", theaters_path %>
</p>

Henslowe/app/views/theaters/index.html.erb
<% title "Theaters" %>

<table class="table-striped">
  <tr valign="top">
    <th>Name</th>
    <th>Street Address</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone Number</th>
    <th>Web Site</th>
    <th>Mission Statement</th>
  </tr>
  <% for theater in @theaters %>
      <tr valign="top">
        <td><%=h theater.name %></td>
        <td><%=h theater.street_address %></td>
        <td><%=h theater.state %></td>
        <td><%=h theater.zip %></td>
        <td><%=h theater.phone_number %></td>
        <td><%=h theater.website %></td>
        <td><%= theater.mission_statement.html_safe %></td>
        <td><%= link_to "Show", theater %></td>
        <td><%= link_to "Edit", edit_theater_path(theater) %></td>
        <td><%= link_to "Destroy", theater, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
     <% end %>
</table>
<p><%= link_to "New Theater", new_theater_path %></p>

Henslowe/app/views/theaters/new.html.erb
<% title "New Theater" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", theaters_path %></p>

Henslowe/app/views/theaters/show.html.erb
<% title "#{@theater.name}" %>

<p>
  <strong>Street Address:</strong>
  <%=h @theater.street_address %>
</p>
<p>
  <strong>State:</strong>
  <%=h @theater.state %>
</p>
<p>
  <strong>Zip:</strong>
  <%=h @theater.zip %>
</p>
<p>
  <strong>Phone Number:</strong>
  <%=h @theater.phone_number %>
</p>
<p>
  <strong>Web Site:</strong>
  <%=h @theater.website %>
</p>
<p>
  <strong>Mission Statement:</strong>
  <%= @theater.mission_statement.html_safe %>
</p>
<p>
  <strong>Calendar ID:</strong>
  <%=h @theater.calendar %>
</p>
  <% unless @theater.calendar.empty? %>
    <%= @theater.embed_calendar.html_safe %><br />
  <% end %>

<strong>Performance and Rehearsal Spaces:</strong><br />
<% @theater.spaces.each do |space| %>
  <%= link_to "#{space.name}", theater_space_path(@theater, space) %><br />
<% end %><br />
<%= link_to "Make new space", new_theater_space_path(@theater) %> 
<p>
  <strong>Current Productions:</strong>
  <% @theater.productions.each do |p| %>
    <% if p.is_current? %>
      <%= link_to "#{p.play.title}", theater_production_path(@theater, p) %><br />
    <% end %>
  <% end %>
</p>
<p>
  <strong>Upcoming Productions:</strong>
  <% @theater.productions.each do |p| %>
    <% if p.is_future? %>
      <%= link_to "#{p.play.title}", theater_production_path(@theater, p) %><br />
    <% end %>
  <% end %>
</p>
<p>
  <strong>Past Productions:</strong>
  <% @theater.productions.each do |p| %>
    <% if p.is_past? %>
      <%= link_to "#{p.play.title}", theater_production_path(@theater, p) %><br />
    <% end %>
  <% end %>
</p>
<p>
  <%= link_to "Make new production", new_theater_production_path(@theater) %> | 
</p>
<p><strong>Users:</strong>
  <% users =  @theater.users.uniq %>
  <% users.each do |user| %>
    <%= link_to "#{user.name}", user %> -- <% user.jobs.each do |job| %><%= job.niche.title %> <% unless job.production_id.nil? %>on <%= job.production.play.title %><% end %><% unless job == user.jobs.last %>, <% end %><% end %>
  <% end %>
</p> 
  <%= link_to "Create New Job", new_theater_job_path(@theater) %>
  
  <%= link_to "Edit", edit_theater_path(@theater) %> |
  <%= link_to "Destroy", @theater, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", theaters_path %>
</p>