Henslowe/config/routes.rb
Henslowe::Application.routes.draw do
  root :to => 'theaters#index'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy"
  resources :authors

  resources :niches

  resources :theaters do |theater|
    resources :spaces
    resources :productions do
      member do
        get 'doubling'
        get 'bulk_scheduler'
      end
    end
    resources :users
    resources :jobs
  end

  resources :productions do
    resources :rehearsals
  end

  resources :plays do	
    resources :characters
    resources :acts do 
      resources :scenes do
        resources :french_scenes
      end
    end
  end

  resources :acts do 
    resources :scenes, :french_scenes
  end

  resources :scenes do 
    resources :french_scenes
  end

  resources :users do
    resources :productions
  end

end

Henslowe/app/models/space.rb
class Space < ActiveRecord::Base
  belongs_to :theater
  attr_accessible :address, :name, :seating_capacity, :theater_id, :calendar

   def embed_calendar
  	embed_code_start = "<iframe src=\"https://www.google.com/calendar/embed?showTitle=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src="
    embed_code_finish = "&amp;color=%23B1440E&amp;ctz=America%2FNew_York\" style=\" border-width:0 \" width=\"800\" height=\"600\" frameborder=\"0\" scrolling=\"no\"></iframe>"
    s = self.calendar
  	embed = embed_code_start + s + embed_code_finish
  end
end

Henslowe/app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
before_filter :load_theater

  def index
    @spaces = @theater.spaces.all(:order => "name")
  end
  
  def show
    @space = @theater.spaces.find(params[:id])
  end
  
  def new
    @space = @theater.spaces.new
  end
  
  def create
    @space = @theater.spaces.new(params[:space])
    if @space.save
      flash[:notice] = "Successfully created space."
      redirect_to [@theater, @space]
    else
      render :action => 'new'
    end
  end
  
  def edit
    @space = @theater.spaces.find(params[:id])
  end
  
  def update
    @space = @theater.spaces.find(params[:id])
   if @space.update_attributes(params[:space])
      redirect_to [@theater, @space]
   else
      render :action => 'edit'
    end
  end
  
  def destroy
    @space = @theater.spaces.find(params[:id])
    @space.destroy
    flash[:notice] = "Successfully destroyed space."
    redirect_to theater_spaces_url(@theater)
  end

private
  def load_theater
    @theater = Theater.find(params[:theater_id])
  end
end

Henslowe/app/helpers/spaces_helper.rb
module SpacesHelper
end

Henslowe/app/views/spaces/_form.html.erb
<%= semantic_form_for [@theater, @space] do |f| %>
  <%= f.inputs :name, :address, :seating_capacity, :calendar %>


  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

Henslowe/app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

Henslowe/app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Seating capacity</th>
    <th>Theater</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.address %></td>
    <td><%= space.seating_capacity %></td>
    <td><%= space.theater %></td>
    <td><%= link_to 'Show', space %></td>
    <td><%= link_to 'Edit', edit_space_path(space) %></td>
    <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Space', new_space_path %>

Henslowe/app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', theater_spaces_path(@theater) %>

Henslowe/app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @space.name %>
</p>

<p>
  <b>Address:</b>
  <%= @space.address %>
</p>

<p>
  <b>Seating capacity:</b>
  <%= @space.seating_capacity %>
</p>

<%= @space.embed_calendar.html_safe %><br />


<%= link_to 'Edit', edit_theater_space_path(@theater, @space) %> |
<%= link_to "Back to #{@theater.name}", theater_path(@theater) %>