Henslowe/config/routes.rb
Henslowe::Application.routes.draw do
  root :to => 'theaters#index'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy"
  resources :authors

  resources :niches

  resources :theaters do |theater|
    resources :spaces
    resources :productions do
      member do
        get 'doubling'
        get 'bulk_scheduler'
      end
    end
    resources :users
    resources :jobs
  end

  resources :productions do
    resources :rehearsals
  end

  resources :plays do	
    resources :characters
    resources :acts do 
      resources :scenes do
        resources :french_scenes
      end
    end
  end

  resources :acts do 
    resources :scenes, :french_scenes
  end

  resources :scenes do 
    resources :french_scenes
  end

  resources :users do
    resources :productions
  end

end

Henslowe/app/models/scene.rb
class Scene < ActiveRecord::Base
  before_create :set_defaults 

  belongs_to :play
  belongs_to :act
  attr_accessible :scene_number, :french_scenes_attributes, :play_id, :act_id

  has_many :french_scenes, :dependent => :destroy
  accepts_nested_attributes_for :french_scenes, :allow_destroy => :true
  has_many :characters, :through => :french_scenes
  default_scope :order => 'scene_number'

  def full_path
    path = self.act.act_number.to_s + "." + self.scene_number.to_s
    path.to_s
    return path
  end
  
  def pretty_name
    name = "Scene " + self.full_path
  end

  def set_defaults
    act = self.act
    self.play_id = act.play_id
  end

  def actors_called(production)
    actors = []
    for fs in self.french_scenes do 
      fs.actors_called(production).each do |a|
        unless actors.include?(a)
          actors << a
          actors.sort! {|a, b| a.first_name <=> b.first_name }
        end
      end
    end
    return actors
  end
end

Henslowe/app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_filter :load_act
  def index
    @scenes = @act.scenes.all
  end
  
  def show
    @scene = Scene.find(params[:id])
  end
  
  def new
    @scene = @act.scenes.new
  end
  
  def create
    @scene = @act.scenes.new(params[:scene])
    if @scene.save
      flash[:notice] = "Successfully created scene."
      redirect_to [@act, @scene]
    else
      render :action => 'new'
    end
  end
  
  def edit
    @scene = @act.scenes.find(params[:id])
  end
  
  def update
    @scene = @act.scenes.find(params[:id])
    if @scene.update_attributes(params[:scene])
      flash[:notice] = "Successfully updated scene."
      redirect_to [@act, @scene]
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @scene = @act.scenes.find(params[:id])
    @scene.destroy
    flash[:notice] = "Successfully destroyed scene."
    redirect_to act_scenes_path(@act)
  end
  private
 
  def load_act
    @act = Act.find(params[:act_id])
  end
end

Henslowe/app/helpers/scenes_helper.rb
module ScenesHelper
end

Henslowe/app/views/shared/scenes/_form.html.erb
<%= semantic_form_for [@act, @scene] do |f| %>
  <%= f.inputs %>
<%= f.actions %>
  
<% end %>

Henslowe/app/views/shared/scenes/edit.html.erb
<% title "Edit Scene #{@scene.scene_number}" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", [@act, @scene] %> |
  <%= link_to "View All", scenes_path %>
</p>

Henslowe/app/views/shared/scenes/index.html.erb
<% title "#{@scene.play.title} Act #{@scene.act.act_number} Scenes" %>

<table>
  <tr>
    <th>Number</th>
  </tr>
  <% for scene in @scenes %>
    <tr>
      <td><%=h scene.scene_number %></td>
      <td><%= link_to "Show", act_scene_path(@act, scene) %></td>
      <td><%= link_to "Edit", edit_act_scene_path(@act, scene) %></td>
      <td><%= link_to "Destroy", [@act, scene], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Scene", new_act_scene_path(@act) %></p>

Henslowe/app/views/shared/scenes/new.html.erb
<% title "New Scene" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", act_scenes_path(@act) %></p>

Henslowe/app/views/shared/scenes/show.html.erb
<% title "#{@scene.play.title} Act #{@scene.act.act_number}, Scene #{@scene.scene_number}" %>

<p>
  <strong>Characters:</strong><br />
  <% c = @scene.on_stage %>
  <ul> 
  <% c.each do |char| %>
    <li><%= char.name %></li>
  <% end %>
  </ul>
</p>
<p>
  <strong>French Scenes:</strong><br />
  <ul>
  <% for french_scene in @scene.french_scenes do %>
    <li><%= french_scene.french_scene_number %> <%= link_to 'Show', scene_french_scene_path(@scene, french_scene) %><%= link_to 'Edit', edit_scene_french_scene_path(@scene, french_scene) %><%= link_to 'Destroy', [@scene, french_scene], confirm: 'Are you sure?', :method => :delete %></li>
  <% end %>
  </ul>
</p>

<p>
  <%= link_to "View Act #{@scene.act.act_number}", play_act_path(@scene.play, @scene.act) %>
</p>