Henslowe/config/routes.rb
Henslowe::Application.routes.draw do
  root :to => 'theaters#index'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy"
  resources :authors

  resources :niches

  resources :theaters do |theater|
    resources :spaces
    resources :productions do
      member do
        get 'doubling'
        get 'bulk_scheduler'
      end
    end
    resources :users
    resources :jobs
  end

  resources :productions do
    resources :rehearsals
  end

  resources :plays do	
    resources :characters
    resources :acts do 
      resources :scenes do
        resources :french_scenes
      end
    end
  end

  resources :acts do 
    resources :scenes, :french_scenes
  end

  resources :scenes do 
    resources :french_scenes
  end

  resources :users do
    resources :productions
  end

end

Henslowe/app/models/play.rb
class Play < ActiveRecord::Base
  attr_accessible :title, :date, :number_of_acts, :acts_attributes, :characters_attributes, :scenes_attributes, :author_id, :author_first_name, :author_last_name
  attr_accessor :number_of_acts, :author_first_name, :author_last_name

  has_many :productions, :dependent => :destroy
  has_many :theaters, :through => :productions
  has_many :acts, :dependent => :destroy
  accepts_nested_attributes_for :acts, :allow_destroy => true
  has_many :scenes, :through => :acts
  has_many :french_scenes, :through => :scenes
  has_many :characters
  accepts_nested_attributes_for :characters, :allow_destroy => true
  
  belongs_to :author
  accepts_nested_attributes_for :author
  
  default_scope { order('authors.last_name').includes(:author) } 
  
  def total_characters
  #determines number of characters in play
    self.characters.size
  end
  
  def total_male_characters
  #determines number of male characters in play
    men = 0
    self.characters.each do |c|
      unless c.is_female?
        men+=1
      end
    end
    return men
  end
 
  def total_female_characters
  #determines number of female characters in play
    women = 0
    self.characters.each do |c|
      if c.is_female?
        women+=1
      end
    end
    return women
  end
end

Henslowe/app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @plays = Play.all
  end
  
  def show
    @play = Play.find(params[:id])
  end
  
  def new
    @play = Play.new
  end
  
  def create
    @play = Play.new(params[:play])
    number_of_acts = @play.number_of_acts.to_i
    n = 1
    number_of_acts.times do 
      act = @play.acts.build(:act_number => n)
      1.times {act.scenes.build(:scene_number => 1)}
      n +=1
    end
    if @play.author_first_name && @play.author_last_name
      author = Author.create(:first_name => @play.author_first_name, :last_name => @play.author_last_name)
      @play.author = author
    end
    if @play.save
      flash[:notice] = "Successfully created play."
      redirect_to @play
    else
      render :action => 'new'
    end
  end
  
  def edit
    @play = Play.find(params[:id])
  end
  
  def update
    @play = Play.find(params[:id])
    if @play.update_attributes(params[:play])
      flash[:notice] = "Successfully updated play."
      redirect_to @play
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @play = Play.find(params[:id])
    @play.destroy
    flash[:notice] = "Successfully destroyed play."
    redirect_to plays_url
  end
end

Henslowe/app/helpers/plays_helper.rb
module PlaysHelper
end

Henslowe/app/views/plays/_act_fields.erb
<p class="nested-fields">
	<%= f.input :act_number, :required => true %>
	<div id="scenes">
		<%= f.semantic_fields_for :scenes do |scene| %>
			<%= render 'scene_fields', :f => scene %>
		<% end %>
		<%= link_to_add_association "Add a Scene", f, :scenes %> 
	</div>
	<%= link_to_remove_association "Remove Act", f %><br /> 
  <hr>

Henslowe/app/views/plays/_character_fields.erb
<p class="fields">
<%= f.inputs %>
</p>

Henslowe/app/views/plays/_form.html.erb
<%= semantic_form_for @play do |f| %>
  <%= f.input :title, :required => true %>
  <%= f.input :date, :as => :date_picker, :hint => "If you don't know the exact date, please set as much as you know and put dummy values, like \'Jan 1\'." %>
  <%= f.input :author, :allow_blank => false %>
  <div id='acts'>
  <%= f.semantic_fields_for :acts do |act| %>
  <%= render 'act_fields', :f => act %>
        <% end %>
	<%= link_to_add_association 'Add an Act', f, :acts %>
  </div>
<%= f.actions %>
<% end %>

Henslowe/app/views/plays/_french_scene_fields.erb
<p class="nested-fields">
<%= f.input :french_scene_number, :required => true, :hint => "French scenes usually are letters (a, b, c)" %>
<%= f.input :characters, :as => :check_boxes, :collection => @play.characters.all %>
<%= link_to_remove_association "Remove French Scene", f %>
</p>
<hr>

Henslowe/app/views/plays/_scene_fields.erb
<p class="nested-fields">
<%= f.input :scene_number, :required => true  %>
</p>
  <div id='french_scenes'>
        <%= f.semantic_fields_for :french_scenes do |fs| %>
          <%= render 'french_scene_fields', :f => fs %>
        <% end %>
  </div>
  <%= link_to_add_association "Add a french scene", f, :french_scenes %><br />
<%= link_to_remove_association "Remove Scene", f %>
<hr>

Henslowe/app/views/plays/edit.html.erb
<% title "Editing #{@play.title} " %>
<%= render :partial => 'form' %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

Henslowe/app/views/plays/index.html.erb
<% title "All Plays" %>

<table class="table-striped">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Publication Date</th>
    <th></th><th></th>
  </tr>
  <% for play in @plays %>
    <tr>
      <td><% if play.author %><%= link_to "#{play.author.name}", author_path(play.author) %><% end %></td>
      <td><%= link_to "#{play.title}", play_path(play) %></td>
      <td><%=h play.date %></td>
      <td><%= link_to "Edit", edit_play_path(play) %></td>
      <td><%= link_to "Destroy", play, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Play", new_play_path %></p>

Henslowe/app/views/plays/new.html.erb
<% title "New Play" %>
<%= semantic_form_for @play do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :author, :as => :select %>
    <%= f.input :author_first_name, :label => "If the author is not listed, please provide their first and last names here" %><%= f.input :author_last_name %>
    <%= f.input :date, :as => :date_picker %>
  	<%= f.input :number_of_acts %>
  <% end %>
<%= f.actions %>
<% end %>
<p><%= link_to "Back to List", plays_path %></p>

Henslowe/app/views/plays/show.html.erb
<% title "#{@play.title}" %>
<p>
  <strong>Publication Date:</strong>
  <%=h @play.date %>
</p>
<p>
  <strong>Author:</strong>
  <%= link_to "#{@play.author.name}", author_path(@play.author) %>
</p>
<p>
  <strong>Productions:</strong>
  <ul>
  <% @play.productions.each do |p| %>
    <li><%= link_to "#{p.theater.name}", theater_path(p.theater) %>: <%= p.start_date %> - <%= p.end_date %></li>
  <% end %>
</ul>
</p>

<strong> Scene Chart </strong>
  <table border = "1" class="table-striped">
    <tr><th>Character</th>
      <% @play.acts.each do |a| %>
        <% a.scenes.each do |s| %>
          <% s.french_scenes.each do |fs| %>
            <th><%= a.act_number %>.<%= fs.scene.scene_number %>.<%= fs.french_scene_number %></th>
          <% end %>
        <% end %>
      <% end %>
    </tr>
    <% @play.characters.each do |character| %>
      <tr><td><%= character.name %> <em><%= link_to 'Show', play_character_path(@play, character) %> <%= link_to "Edit", edit_play_character_path(@play, character) %> <%= link_to 'Destroy', [@play, character], :confirm => 'Are you sure?', :method => :delete %></em></td>
      <% @play.acts.each do |a| %>
        <% a.scenes.each do |s| %>
          <% s.french_scenes.each do |fs| %>
            <td><% if fs.characters.include?(character) %>
               <%= character.name %>
            <% end %>
          <% end %></td>
        <% end %>
      <% end %>
    <% end %></tr>
  </table>
</p>

<%= link_to 'Add Character', new_play_character_path(@play) %>
<p>
  <strong>Acts:</strong><br />
  <ul>
  <% for act in @play.acts %>
    <li>Act <%= act.act_number %> (<%= link_to "Edit", edit_play_act_path(@play, act) %>) -- (<%= act.id %>)<br /><ul>
    <% for scene in act.scenes %>
      <li><%= act.act_number %>.<%= scene.scene_number %> -- ( <%= scene.id %> )<br /><ul>
    <% for french_scene in scene.french_scenes %>
      <li><%= act.act_number %>.<%= scene.scene_number %>.<%= french_scene.french_scene_number %> (<%= french_scene.id %>)<ul><% french_scene.characters.each do |character|%><li><%= character.name %><% end %></uL></li>

      <% end %></ul>
    <% end %></ul>
  <% end %></ul>
</p>




<p>
  <%= link_to "Edit", edit_play_path(@play) %> |
  <%= link_to "Destroy", @play, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", plays_path %>
</p>